version: "3"

services:
  backend:

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_USER: "petclinic"
      MYSQL_PASSWORD: "petclinic"
      MYSQL_DATABASE: "petclinic"
    volumes:
      - "./src/main/resources/db/mysql/user.sql:/docker-entrypoint-initdb.d/user.sql"