pipeline:
  identifier: Build_bravoris_spring_petclinic_project_testing_1715070793211
  name: Build spring-petclinic-project-testing
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: bravoris/spring-petclinic-project-testing
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: echo
                  spec:
                    shell: Sh
                    command: echo hello world, starting harness ci
                  timeout: ""
                  type: Run
              - step:
                  identifier: scalabuild
                  name: scala_build
                  spec:
                    command: "gradle build "
                  timeout: ""
                  type: Run
              - step:
                  identifier: scalatest
                  name: scala_test
                  spec:
                    command: "./gradlew test\n\t\txml_file=$(find /harness/build/test-results/test -type f -name \"*.xml\" | head -n 1)\n\n\t\tif [ -n \"$xml_file\" ]; then\n\t\t\tcp \"$xml_file\" /harness/reports.xml\n\t\t\techo \"XML file copied to /harness/reports.xml\"\n\t\telse\n\t\t\techo \"No XML file found in /path\"\n\t\tfi"
                    reports:
                      spec:
                        paths:
                          - /harness/reports.xml
                      type: JUnit
                  timeout: ""
                  type: Run
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: rishhe
                    repo: rishhe/pet-clinic
                    tags:
                      - latest
                    dockerfile: Dockerfile
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
        type: CI
