pipeline:
  identifier: Build_bravoris_spring_petclinic_project_testing_1715070793211
  name: Build spring-petclinic-project-testing
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: bravoris/spring-petclinic-project-testing
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: echo
                  spec:
                    shell: Sh
                    command: echo hello world, starting harness ci
                  timeout: ""
                  type: Run
              - step:
                  identifier: scalabuild
                  name: maven_build
                  spec:
                    shell: Sh
                    command: |-
                      export M2_HOME=/opt/apache-maven-3.9.6
                      export PATH=$M2_HOME/bin:$PATH

                      mvn clean install -Dtest=!PostgresIntegrationTests
                  timeout: ""
                  type: Run
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: rishhe
                    repo: rishhe/pet-clinic
                    tags:
                      - latest
                    dockerfile: Dockerfile
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
        type: CI
        delegateSelectors:
          - docker-delegate
